In [1015]:
# Librarys

import numpy as np
import random

SEED = 20

In [1016]:
np.random.seed(SEED)
# Generating our DataBase using Random numbers, Randomizing numbers between 0 and 1. 1 represents 'yes' and 0 represents 'no'
proportion1 = 0.7
proportion2 = 0.3
# I am providing a skewed distribution to the model to capture potential patterns
X = np.random.choice([0, 1], size=(500, 3), p=[1 - proportion1, proportion1])
y = np.random.choice([0, 1], size=(500, 1), p=[1 - proportion2, proportion2])
#X
print(np.unique(X, return_counts=True))

(array([0, 1]), array([ 446, 1054]))


In [1017]:
#y
print(np.unique(y, return_counts=True))

(array([0, 1]), array([351, 149]))


In [1018]:
# Creating a class for the Neuron. This neuron will have a list with weights and BIAS
class Neuron:
    def __init__(self):
        self.features = None
        self.neurons = None

    # We need to use the features as parameters to know how many weights we will have and the number of neurons to determine the quantity of BIAS
    # As we are using a Perceptron, evidently, we will have only one neuron, so the BIAS will have only one value assigned to that neuron
    # It was necessary to create the object without parameters and then add them later in a loop structure, so we needed to create a function to assign the attributes as parameters
    def values_assignment(self, features, neurons):
        self._weights = np.zeros(len(features))
        self._bias = np.zeros(neurons)

    # Add the value for the respective Weight
    def add_weights(self, index_cols, delta_wj):
        self._weights[index_cols] = self._weights[index_cols] + delta_wj

    def add_bias(self, delta_bias):
        self._bias[0] = self._bias[0] + delta_bias

    # Our sigmoid function
    def sigmoid(self, x):
      return 1 / (1 + np.exp(-x))

    # Checking the activation of the Neuron with a Step Function
    def activation_check(self, features, output):
        threshold = 0.8
        # Weighted sum to input into our activation function
        weighted_sum = (np.dot(features, self._weights) + self._bias)
        # Activation function using our Weighted sum
        sigmoid_function = self.sigmoid(weighted_sum)
        # If the result is greater than threshold, so the Neuron activate
        if sigmoid_function > threshold:
            self.checking_prediction = 1
            if self.checking_prediction == output:
                return True
            else:
                return False
        else:
            self.checking_prediction = 0
            if self.checking_prediction == output:
                return True
            else:
                return False

    def __str__(self):
        return f'Weights: {self._weights} | BIAS: {self._bias}'

In [1019]:
# Instantiating the object neuron
neuron = Neuron()
# The learning rate constant
η = 0.08
# Used these variables to calculate the accuracy of the model
trys = 0
corrects = 0

for i in range(25):
  # Creating a Loop to walk through the vector X
  for index_row, row in enumerate(X):
      trys += 1
      # Checking if is the 1st time of the loop, if yes, we create the weights based on ours features
      if index_row == 0:
          neuron.values_assignment(row, 1)

      # Calling the method 'activation_check' to instance the attribute "checking_prediction"
      neuron.activation_check(row, y[index_row])

      # Here is where our perceptron works
      # 1st we are checking if the neuron DON'T activade, if Don't, it means we need fit the Weights
      if neuron.activation_check(row, y[index_row]) == False:
          # Loop to walk through the columns, so we can calculate the weights for each feature specifically
          for index_col, col in enumerate(row):
                  # Using the basic function of perceptrons to calculate the weights
                  delta_wj = η * (y[index_row] - neuron.checking_prediction) * col
                  # This part call the method "add_weights" to add the weight on the respective index of the weight vector
                  neuron.add_weights(index_col, delta_wj)
          '''I needed to work with the BIAS separately from the weights, to be able to calculate it independently. However, the function remains the same, with the only change being in X[0]
          as the bias will always be 1'''
          delta_bias = η * (y[index_row] - neuron.checking_prediction) * 1
          # Same with weights, just adding the bias to the BIAS vector
          neuron.add_bias(delta_bias)
      else:
          corrects += 1

# Accuracy mathematics
print(f'Total: {trys}')
print(f'Prediction: {corrects}')

accuracy = corrects / trys
print(f'Accuracy of the train model: {accuracy*100:.2f}%')

<ipython-input-1018-0d49cdf98921>:16: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  self._weights[index_cols] = self._weights[index_cols] + delta_wj
<ipython-input-1018-0d49cdf98921>:19: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  self._bias[0] = self._bias[0] + delta_bias


Total: 12500
Prediction: 7425
Accuracy of the train model: 59.40%


In [1020]:
# Creating our test dataset to validate the model
SEED = 15
np.random.seed(SEED)
X_test = np.random.choice([0, 1], size=(500, 3), p=[1 - proportion1, proportion1])
y_test = np.random.choice([0, 1], size=(500, 1), p=[1 - proportion2, proportion2])


In [1021]:
# The distribuition of 0 and 1 in X_test
print(np.unique(X_test, return_counts=True))

(array([0, 1]), array([ 438, 1062]))


In [1022]:
# Idem for Y
print(np.unique(y_test, return_counts=True))

(array([0, 1]), array([343, 157]))


In [1023]:
trys_test = 0
corrects_test = 0
dummy_predictions = 0

# Same logic used in the cell above, but here I am predicting Y based on a new test dataset that we also randomly selected values for.
for index_row, row in enumerate(X_test):
    trys_test += 1

    neuron.activation_check(row, y_test[index_row])

    if neuron.checking_prediction:
      if neuron.checking_prediction == y_test[index_row]:
        corrects_test += 1

    else:
      if neuron.checking_prediction == y_test[index_row]:
        dummy_predictions += 1
        corrects_test += 1



# Accuracy mathematics
print(f'Total: {trys_test}')
print(f'Prediction: {corrects_test}')

accuracy_test = corrects_test / trys_test
dummy_accuracy_test = dummy_predictions / trys_test

print(f'The prediction accuracy of the DUMMY model was: {dummy_accuracy_test*100}%')
print(f'The prediction accuracy of the PERCEPTRON model was: {accuracy_test*100}%')

Total: 500
Prediction: 308
The prediction accuracy of the DUMMY model was: 54.0%
The prediction accuracy of the PERCEPTRON model was: 61.6%
