In [1]:
# Librarys

import numpy as np
import random

SEED = 20

In [2]:
# Creating our Zeros Data Matrix, using numpy
X = np.zeros((10,3), dtype=int)
y = np.zeros((10,1), dtype=int)
X

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [3]:
y

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]])

In [4]:
# Generating our DataBase using Random numbers, Randomizing numbers between 0 and 1, where 1 represents 'yes' and 0 represents 'no'
# First, generating our Features (X)
random.seed(SEED)
for index_row, row in enumerate(X):
    for index_col, col in enumerate(row):
        X[index_row][index_col] = random.randint(0,1)
X

array([[0, 1, 0],
       [1, 0, 0],
       [1, 1, 0],
       [0, 0, 1],
       [1, 1, 1],
       [0, 0, 1],
       [1, 1, 1],
       [0, 1, 1],
       [0, 0, 0],
       [0, 0, 0]])

In [5]:
# Generating our label (Y)
for index_col, col in enumerate(y):
    y[index_col] = random.randint(0,1)
y

array([[0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1]])

In [9]:
# Creating a class for the Neuron. This neuron will have a list with weights and BIAS
class Neuron:
    def __init__(self):
        self.features = None
        self.neurons = None

    # We need to use the features as parameters to know how many weights we will have and the number of neurons to determine the quantity of BIAS
    # As we are using a Perceptron, evidently, we will have only one neuron, so the BIAS will have only one value assigned to that neuron
    # It was necessary to create the object without parameters and then add them later in a loop structure, so we needed to create a function to assign the attributes as parameters
    def values_assignment(self, features, neurons):
        self._weights = np.zeros(len(features))
        self._bias = np.zeros(neurons)

    # Add the value for the respective Weight
    def add_weights(self, index_cols, delta_wj):
        self._weights[index_cols] = self._weights[index_cols] + delta_wj

    def add_bias(self, delta_bias):
        self._bias[0] = self._bias[0] + delta_bias

    # Checking the activation of the Neuron with a Step Function
    def activation_check(self, features, output):
        # If the results of the function return more than 0, so the prediction is 1, else return 0. Then, we need verify if the prediction is equal to the output
        if (np.dot(features, self._weights) + self._bias) > 0:
            self.checking_prediction = 1
            if self.checking_prediction == output:
                return True
            else:
                return False
        else:
            self.checking_prediction = 0
            if self.checking_prediction == output:
                return True
            else:
                return False

    def __str__(self):
        return f'Weights: {self._weights} | BIAS: {self._bias}'

In [10]:
# Instantiating the object neuron
neuron = Neuron()
# The learning rate constant
η = 0.1
# Used these variables to calculate the accuracy of the model
trys = 0
corrects = 0

# Creating a Loop to walk through the vector X
for index_row, row in enumerate(X):
    trys += 1
    # Checking if is the 1st time of the loop, if yes, we create the weights based on ours features
    if index_row == 0:
        neuron.values_assignment(row, 1)

    #Just some visual things to ilustrate the model
    print(f'Features: {row}')
    print(f'{neuron}')
    print(f'Label: {y[index_row]}')
    print(f'Prediction: {1 if neuron.activation_check(row, y[index_row]) else 0}')
    print()

    # Here is where our perceptron works
    # 1st we are checking if the neuron DON'T activade, if Don't, it means we need fit the Weights
    if neuron.activation_check(row, y[index_row]) == False:
        # Loop to walk through the columns, so we can calculate the weights for each feature specifically
        for index_col, col in enumerate(row):
                # Using the basic function of perceptrons to calculate the weights
                delta_wj = η * (y[index_row] - neuron.checking_prediction) * col
                # This part call the method "add_weights" to add the weight on the respective index of the weight vector
                neuron.add_weights(index_col, delta_wj)
        '''I needed to work with the BIAS separately from the weights, to be able to calculate it independently. However, the function remains the same, with the only change being in X[0]
        as the bias will always be 1'''
        delta_bias = η * (y[index_row] - neuron.checking_prediction) * 1
        # Same with weights, just adding the bias to the BIAS vector
        neuron.add_bias(delta_bias)
    else:
        corrects += 1

print(trys)
print(corrects)
# Accuracy mathematics
accuracy = corrects / trys
print(f'A acurácia do modelo foi de {accuracy*100}%')

Features: [0 1 0]
Weights: [0. 0. 0.] | BIAS: [0.]
Label: [0]
Prediction: 1

Features: [1 0 0]
Weights: [0. 0. 0.] | BIAS: [0.]
Label: [0]
Prediction: 1

Features: [1 1 0]
Weights: [0. 0. 0.] | BIAS: [0.]
Label: [1]
Prediction: 0

Features: [0 0 1]
Weights: [0.1 0.1 0. ] | BIAS: [0.1]
Label: [1]
Prediction: 1

Features: [1 1 1]
Weights: [0.1 0.1 0. ] | BIAS: [0.1]
Label: [1]
Prediction: 1

Features: [0 0 1]
Weights: [0.1 0.1 0. ] | BIAS: [0.1]
Label: [1]
Prediction: 1

Features: [1 1 1]
Weights: [0.1 0.1 0. ] | BIAS: [0.1]
Label: [0]
Prediction: 0

Features: [0 1 1]
Weights: [ 0.   0.  -0.1] | BIAS: [0.]
Label: [0]
Prediction: 1

Features: [0 0 0]
Weights: [ 0.   0.  -0.1] | BIAS: [0.]
Label: [0]
Prediction: 1

Features: [0 0 0]
Weights: [ 0.   0.  -0.1] | BIAS: [0.]
Label: [1]
Prediction: 0

10
7
A acurácia do modelo foi de 70.0%


<ipython-input-9-96fc5d582758>:16: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  self._weights[index_cols] = self._weights[index_cols] + delta_wj
<ipython-input-9-96fc5d582758>:19: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  self._bias[0] = self._bias[0] + delta_bias
